name: Restrict Branch Creation

on:
  create:
    
jobs:
  restrict_branch_creation:
    runs-on: ubuntu-latest
    steps:
      - name: Check base branch
        run: |
          BASE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [[ "$BASE_BRANCH" == "main" ]]; then
            echo "Branches cannot be created off 'main'. Deleting the branch..."
            git push origin --delete "${GITHUB_REF##*/}"
            exit 1
          fi
