name: Restrict Branch Creation

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  restrict_branch_creation:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Branch is Directly Forked from Main
        run: |
          # Extract the branch name
          BASE_BRANCH=${GITHUB_REF##*/}
          echo "Detected branch: $BASE_BRANCH"

          # Ensure 'main' is the direct parent of the branch
          if [ "$(git log --pretty=%P -n 1 HEAD | grep -o origin/main)" = "origin/main" ]; then
            echo "Branch is forked from main. Create a new branch off of dev and re-implement."
            exit 1
          else
            echo "Branch is not directly forked from main. Proceeding."
          fi
