name: Restrict Branch Creation

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  restrict_main_branching:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if Branch is Directly Forked from Main
        run: |
          # Extract the branch name
          PULLED_FROM=${GITHUB_REF##*/}
          echo "Pulled from: $PULLED_FROM"

          # Get the merge-base between the branch and main
          MERGE_BASE=$(git merge-base HEAD origin/main)
          echo "Common Base: $MERGE_BASE"

          # Check if the branch starts from main
          if [ "$MERGE_BASE" = "$(git rev-parse origin/main)" ]; then
            echo "Branch is forked from main. Create a new branch off of dev and re-implement."
            exit 1
          else
            echo "Branch is not directly forked from main. Proceeding."
          fi
